"""create_position_snapshots_table

Revision ID: 05f8f57da915
Revises: 819296057392
Create Date: 2025-12-23 14:20:07.922106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05f8f57da915'
down_revision: Union[str, None] = 'cc5e36ab37dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_snapshots')
    # ### end Alembic commands ###
