"""create_accounts_table

Revision ID: 652a4d934308
Revises: cdebea52b64f
Create Date: 2025-12-23 14:19:36.190510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652a4d934308'
down_revision: Union[str, None] = 'cdebea52b64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=255), nullable=False),
    sa.Column('broker_account_id', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('margin_available', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
