"""create_risk_events_table

Revision ID: a2ff27f734f9
Revises: 05f8f57da915
Create Date: 2025-12-23 14:20:55.891271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ff27f734f9'
down_revision: Union[str, None] = '05f8f57da915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_events_created_at', 'risk_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_events_created_at', table_name='risk_events')
    op.drop_table('risk_events')
    # ### end Alembic commands ###
