"""create_positions_table

Revision ID: cc5e36ab37dc
Revises: a2ff27f734f9
Create Date: 2025-12-23 14:21:22.165157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5e36ab37dc'
down_revision: Union[str, None] = '819296057392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='unique_account_symbol')
    )
    op.create_index('ix_positions_account_symbol', 'positions', ['account_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index('ix_positions_account_symbol', table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
