"""
Advance / Decline ration (Bars) Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class AdvanceDeclineRationBars:
    """Placeholder implementation for the Advance / Decline ration (Bars) indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Advance / Decline ration (Bars) value once implemented."""
        raise NotImplementedError("Implement the Advance / Decline ration (Bars) calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Advance / Decline ration (Bars) values once implemented."""
        raise NotImplementedError("Implement the rolling Advance / Decline ration (Bars) calculation.")
