"""
Average true range Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class AverageTrueRange:
    """Placeholder implementation for the Average true range indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Average true range value once implemented."""
        raise NotImplementedError("Implement the Average true range calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Average true range values once implemented."""
        raise NotImplementedError("Implement the rolling Average true range calculation.")
