"""
Average directional index Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class AverageDirectionalIndex:
    """Placeholder implementation for the Average directional index indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Average directional index value once implemented."""
        raise NotImplementedError("Implement the Average directional index calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Average directional index values once implemented."""
        raise NotImplementedError("Implement the rolling Average directional index calculation.")
