"""
Bollinger bands %b Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class BollingerBandsB:
    """Placeholder implementation for the Bollinger bands %b indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Bollinger bands %b value once implemented."""
        raise NotImplementedError("Implement the Bollinger bands %b calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Bollinger bands %b values once implemented."""
        raise NotImplementedError("Implement the rolling Bollinger bands %b calculation.")
