"""
Chaikin money flow Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class ChaikinMoneyFlow:
    """Placeholder implementation for the Chaikin money flow indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Chaikin money flow value once implemented."""
        raise NotImplementedError("Implement the Chaikin money flow calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Chaikin money flow values once implemented."""
        raise NotImplementedError("Implement the rolling Chaikin money flow calculation.")
