"""
Chande kroll stop Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class ChandeKrollStop:
    """Placeholder implementation for the Chande kroll stop indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Chande kroll stop value once implemented."""
        raise NotImplementedError("Implement the Chande kroll stop calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Chande kroll stop values once implemented."""
        raise NotImplementedError("Implement the rolling Chande kroll stop calculation.")
