"""
Commodity channel index Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class CommodityChannelIndex:
    """Placeholder implementation for the Commodity channel index indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Commodity channel index value once implemented."""
        raise NotImplementedError("Implement the Commodity channel index calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Commodity channel index values once implemented."""
        raise NotImplementedError("Implement the rolling Commodity channel index calculation.")
