"""
Double EMS Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class DoubleEms:
    """Placeholder implementation for the Double EMS indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Double EMS value once implemented."""
        raise NotImplementedError("Implement the Double EMS calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Double EMS values once implemented."""
        raise NotImplementedError("Implement the rolling Double EMS calculation.")
