"""
Ease of movement Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class EaseOfMovement:
    """Placeholder implementation for the Ease of movement indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Ease of movement value once implemented."""
        raise NotImplementedError("Implement the Ease of movement calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Ease of movement values once implemented."""
        raise NotImplementedError("Implement the rolling Ease of movement calculation.")
