"""
Elder force index Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class ElderForceIndex:
    """Placeholder implementation for the Elder force index indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Elder force index value once implemented."""
        raise NotImplementedError("Implement the Elder force index calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Elder force index values once implemented."""
        raise NotImplementedError("Implement the rolling Elder force index calculation.")
