"""
Hull moving average Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class HullMovingAverage:
    """Placeholder implementation for the Hull moving average indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Hull moving average value once implemented."""
        raise NotImplementedError("Implement the Hull moving average calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Hull moving average values once implemented."""
        raise NotImplementedError("Implement the rolling Hull moving average calculation.")
