"""
Structured catalog of all indicators described in backend/indicators/Indicator.txt.

This module does not calculate the indicator values; it captures metadata such
as usage notes, pros/cons, and ratings so tooling can surface consistent
descriptions in the UI, docs, or strategy builders.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional


@dataclass(frozen=True)
class IndicatorDefinition:
    name: str
    category: str
    description: str
    use: str
    pros: str
    cons: str
    rating: float


INDICATORS: List[IndicatorDefinition] = [
    IndicatorDefinition(
        name="24-Hour Volume",
        category="Volume & Order-Flow",
        description="Rolling sum of traded volume over the last 24 hours.",
        use="Confirm price moves by checking whether activity expands with price.",
        pros="Simple confirmation metric for conviction.",
        cons="Intraday spikes create noise and false positives.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Accumulation/Distribution (A/D)",
        category="Volume & Order-Flow",
        description="Volume-weighted measure distinguishing buying vs selling pressure.",
        use="Watch divergences between price and A/D for reversal clues.",
        pros="Combines price and volume dynamics.",
        cons="Sensitive to single-bar price spikes.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Cumulative Volume Delta (CVD)",
        category="Volume & Order-Flow",
        description="Cumulative difference between taker buy and taker sell volume.",
        use="Highlight persistent buying or selling pressure; divergences matter.",
        pros="Strong order-flow insight when tick data available.",
        cons="Requires high-quality tick/level-2 feeds.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Cumulative Volume Index (CVI)",
        category="Volume & Order-Flow",
        description="Running total of volume that adds/subtracts based on price direction.",
        use="Confirm trend direction via cumulative participation.",
        pros="Simple cumulative perspective.",
        cons="Lagging and insensitive to magnitude.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Net Volume / Up-Down Volume",
        category="Volume & Order-Flow",
        description="Difference between up-volume and down-volume.",
        use="Confirm price direction and detect stealth weakness.",
        pros="Easy to interpret directional volume.",
        cons="Raw numbers often need normalization.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="On-Balance Volume (OBV)",
        category="Volume & Order-Flow",
        description="Adds or subtracts volume based on close direction.",
        use="Look for OBV divergences vs price trend.",
        pros="Very intuitive cumulative approach.",
        cons="Ignores magnitude of price moves.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Money Flow Index (MFI)",
        category="Volume & Order-Flow",
        description="Volume-weighted RSI using typical price.",
        use="Identify overbought/oversold plus volume confirmation.",
        pros="Couples price with volume.",
        cons="False signals in thinly traded markets.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Chaikin Money Flow (CMF)",
        category="Volume & Order-Flow",
        description="A/D style money flow over a set window.",
        use="Bullish/bearish confirmation of money flow.",
        pros="Responsive to recent flow shifts.",
        cons="Whipsaws frequently.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Chaikin Oscillator",
        category="Volume & Order-Flow",
        description="MACD applied to the Accumulation/Distribution line.",
        use="Spot momentum shifts in money flow.",
        pros="Early detection of flow acceleration.",
        cons="Carries MACD noise issues.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Price Volume Trend (PVT)",
        category="Volume & Order-Flow",
        description="Cumulative volume scaled by percent price change.",
        use="Trend confirmation with sensitivity to change size.",
        pros="More responsive than OBV.",
        cons="Still lagging indicator.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Volume Weighted Average Price (VWAP)",
        category="Volume & Order-Flow",
        description="Average price weighted by volume from the session start.",
        use="Intraday support/resistance and execution benchmark.",
        pros="Essential anchor for intraday trading.",
        cons="Resets daily unless anchored.",
        rating=5.0,
    ),
    IndicatorDefinition(
        name="Anchored VWAP",
        category="Volume & Order-Flow",
        description="VWAP anchored to a significant event or swing.",
        use="Dynamic support/resistance tied to chosen anchors.",
        pros="Highly practical once anchor is chosen well.",
        cons="Requires judgement for anchor placement.",
        rating=4.5,
    ),
    IndicatorDefinition(
        name="Volume Weighted Moving Average (VWMA)",
        category="Volume & Order-Flow",
        description="Moving average that weights prices by traded volume.",
        use="Filter trends emphasizing price areas with heavy participation.",
        pros="Focuses on meaningful price levels.",
        cons="Not standardized across tools.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Time Weighted Average Price (TWAP)",
        category="Volume & Order-Flow",
        description="Average price weighted by elapsed time.",
        use="Execution benchmark and simple smoothing.",
        pros="Simple metric for time-slicing orders.",
        cons="Ignores volume dynamics.",
        rating=2.5,
    ),
    IndicatorDefinition(
        name="Volume Oscillator",
        category="Volume & Order-Flow",
        description="Difference between fast and slow volume moving averages.",
        use="Highlight unusual surges relative to trend.",
        pros="Points out abnormal activity.",
        cons="Needs careful parameter tuning.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Advance-Decline Line",
        category="Breadth",
        description="Cumulative difference between advancing and declining issues.",
        use="Confirm market breadth; divergences warn of weakness.",
        pros="Strong read on market health.",
        cons="Requires broad market dataset.",
        rating=4.5,
    ),
    IndicatorDefinition(
        name="Advance-Decline Ratio",
        category="Breadth",
        description="Ratio of advancing to declining issues.",
        use="Spot short-term breadth extremes.",
        pros="Quick snapshot of breadth.",
        cons="Very noisy intraday.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Simple Moving Average (SMA)",
        category="Moving Averages",
        description="Arithmetic mean of prices over a lookback.",
        use="Smooth price for slower trend filters and crossovers.",
        pros="Easy to compute and understand.",
        cons="Lags heavily in fast markets.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Exponential Moving Average (EMA)",
        category="Moving Averages",
        description="Moving average emphasizing recent prices via exponential weights.",
        use="Faster response for crossover systems.",
        pros="More sensitive to new data.",
        cons="Whipsaws in choppy markets.",
        rating=4.5,
    ),
    IndicatorDefinition(
        name="Weighted Moving Average (WMA)",
        category="Moving Averages",
        description="Linear weighting that favors recent prices.",
        use="Compromise between SMA and EMA responsiveness.",
        pros="Balances lag vs smoothness.",
        cons="Less common than EMA, limited adoption.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Smoothed Moving Average",
        category="Moving Averages",
        description="Moving average with additional smoothing to reduce noise.",
        use="Long-term smoothing to reduce whipsaw.",
        pros="Filters a lot of noise.",
        cons="Very laggy response.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Double Exponential Moving Average (DEMA)",
        category="Moving Averages",
        description="Combination of EMAs to reduce lag.",
        use="Capture trend faster than single EMA.",
        pros="Improves responsiveness.",
        cons="Can amplify volatility.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Triple Exponential Moving Average (TEMA)",
        category="Moving Averages",
        description="Triple-smoothed EMA for reduced lag.",
        use="Trend detection with minimal delay.",
        pros="Balances smoothness and speed.",
        cons="Mathematically complex; can magnify noise.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Hull Moving Average (HMA)",
        category="Moving Averages",
        description="Low lag average using sqrt(length) weighting.",
        use="Trend detection with smooth response.",
        pros="Smooth yet responsive output.",
        cons="Some implementations repaint during live bars.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="McGinley Dynamic",
        category="Moving Averages",
        description="Adaptive smoothing line following price more closely.",
        use="Trend-following with reduced whipsaw.",
        pros="Adapts to changing market speed.",
        cons="More complex to tune.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Arnaud Legoux Moving Average (ALMA)",
        category="Moving Averages",
        description="Gaussian-weighted moving average targeting low lag and smoothness.",
        use="Cleaner crossovers with fewer false signals.",
        pros="Visually clean output.",
        cons="Requires sigma/offset tuning.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Least Squares Moving Average (LSMA)",
        category="Moving Averages",
        description="Linear regression-based smoothing of price.",
        use="Estimate underlying slope for trend detection.",
        pros="Offers statistical interpretation.",
        cons="Sensitive to outliers and still lagging.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Linear Regression Channel",
        category="Moving Averages",
        description="Regression line with channel bands capturing variance.",
        use="Trend channels and mean-reversion targets.",
        pros="Quantifiable support/resistance.",
        cons="Outliers can distort slope.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Moving Average Crossover",
        category="Moving Averages",
        description="Signals triggered when a fast MA crosses a slow MA.",
        use="Classic trend entry/exit mechanism.",
        pros="Easy to automate.",
        cons="Lagging with many false signals in ranges.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Moving Average Ribbon",
        category="Moving Averages",
        description="Stack of multiple moving averages with different lengths.",
        use="Visualize trend strength and compression.",
        pros="Great for visual context.",
        cons="Interpreting precise signals is complex.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Relative Strength Index (RSI)",
        category="Momentum & Oscillators",
        description="Momentum oscillator bounded between 0 and 100.",
        use="Overbought/oversold readings and divergence.",
        pros="Versatile and widely adopted.",
        cons="Can remain extreme during strong trends.",
        rating=4.5,
    ),
    IndicatorDefinition(
        name="Stochastic Oscillator",
        category="Momentum & Oscillators",
        description="%K/%D comparing close relative to range.",
        use="Find mean-reversion opportunities and divergences.",
        pros="Solid for choppy markets.",
        cons="Choppy output in strong trends.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Stochastic RSI",
        category="Momentum & Oscillators",
        description="Stochastic calculation applied to RSI values.",
        use="Highlight very short-term extremes.",
        pros="Extremely responsive to changes.",
        cons="Noisy with many false signals.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="MACD",
        category="Momentum & Oscillators",
        description="Difference between two EMAs plus signal line and histogram.",
        use="Momentum shift detection and trend confirmation.",
        pros="Blend of momentum and trend data.",
        cons="Lag in very fast markets.",
        rating=4.5,
    ),
    IndicatorDefinition(
        name="Awesome Oscillator",
        category="Momentum & Oscillators",
        description="Histogram of short vs long SMA of median price.",
        use="Zero-cross, saucer, or peak patterns.",
        pros="Simple momentum read.",
        cons="Dependent on smoothing choices.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Momentum / Rate of Change (ROC)",
        category="Momentum & Oscillators",
        description="Measures raw price changes over lookback.",
        use="Confirm trend strength and spot reversals.",
        pros="Direct, easy to compute.",
        cons="Highly sensitive to period selection.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="TRIX",
        category="Momentum & Oscillators",
        description="Rate of change of a triple-smoothed EMA.",
        use="Filter noise and capture smooth momentum.",
        pros="Less choppy output.",
        cons="Very lagging.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="True Strength Index (TSI)",
        category="Momentum & Oscillators",
        description="Momentum oscillator using double-smoothed price changes.",
        use="Trend strength assessment and divergence.",
        pros="Smooth momentum measure.",
        cons="Needs parameter tuning.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Ultimate Oscillator",
        category="Momentum & Oscillators",
        description="Weighted momentum blend across three timeframes.",
        use="Divergence and confirmation with reduced timeframe bias.",
        pros="Combines multiple horizons.",
        cons="Complex to interpret.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Connors RSI",
        category="Momentum & Oscillators",
        description="Composite of short RSI, streak, and ROC elements.",
        use="Short-term mean-reversion pullbacks.",
        pros="High-probability entries for pullback traders.",
        cons="Tailored to very short holding periods.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Commodity Channel Index (CCI)",
        category="Momentum & Oscillators",
        description="Deviation of price from its moving average.",
        use="Identify trend strength and overbought/oversold zones.",
        pros="Wide dynamic range for signal strength.",
        cons="Unbounded and requires interpretation.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Fisher Transform",
        category="Momentum & Oscillators",
        description="Transforms prices for sharper turning signals.",
        use="Pinpoint reversals via clear peaks and troughs.",
        pros="Produces crisp signals.",
        cons="Prone to whipsaws.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Williams Alligator",
        category="Momentum & Oscillators",
        description="Three smoothed MAs representing market sleep/awakening.",
        use="Avoid trading during alligator sleep, follow when jaws open.",
        pros="Visual representation of market phases.",
        cons="Many parameters and inherent lag.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Stochastic Momentum Index (SMI)",
        category="Momentum & Oscillators",
        description="Refined stochastic measuring distance from median.",
        use="Clearer signals than standard stochastic.",
        pros="Smoother oscillator.",
        cons="Still choppy in trendless markets.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Relative Vigor Index (RVI)",
        category="Momentum & Oscillators",
        description="Compares close vs open to gauge conviction.",
        use="Momentum confirmation with centerline cross.",
        pros="Complimentary to RSI/MACD.",
        cons="Less popular; best used with other tools.",
        rating=2.5,
    ),
    IndicatorDefinition(
        name="Know Sure Thing (KST)",
        category="Momentum & Oscillators",
        description="Multiple ROC sums with smoothing for long-term momentum.",
        use="Capture multi-period trend turns.",
        pros="Incorporates several timeframes.",
        cons="Lagging and parameter-heavy.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="RSI Divergence Detector",
        category="Momentum & Oscillators",
        description="Algorithm that highlights RSI divergences vs price.",
        use="Spot probable reversals when RSI diverges.",
        pros="High value when divergences form.",
        cons="Divergences can persist before price reacts.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Average Directional Index (ADX / DMI)",
        category="Trend Strength",
        description="ADX measures trend strength while +DI/−DI show direction.",
        use="ADX above ~25 confirms trend; DI crosses signal shifts.",
        pros="Separates strength from direction.",
        cons="Lagging indicator.",
        rating=4.5,
    ),
    IndicatorDefinition(
        name="Parabolic SAR",
        category="Trend Strength",
        description="Trailing stop dots that flip when trend reverses.",
        use="Dynamic stop placement and reversal cues.",
        pros="Simple exit/entry rules.",
        cons="Whipsaw prone in ranges.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Ichimoku Cloud",
        category="Trend Strength",
        description="Multi-component system for trend, support/resistance, and momentum.",
        use="Cloud direction, Tenkan/Kijun cross, and lagging span analysis.",
        pros="All-in-one framework.",
        cons="Steep learning curve; defaults may not suit all markets.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Aroon",
        category="Trend Strength",
        description="Measures time since recent highs/lows.",
        use="Identify emerging trends or consolidations.",
        pros="Helpful timing tool for breakouts.",
        cons="Noisy on low timeframes.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Vortex Indicator",
        category="Trend Strength",
        description="Trend vigor measure derived from directional movement.",
        use="Confirm whether trend is reliable.",
        pros="Adds conviction to trend trades.",
        cons="Multiple variants; parameter sensitivity.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Supertrend",
        category="Trend Strength",
        description="ATR-based trailing indicator with buy/sell flips.",
        use="Ride trending markets with clear stop lines.",
        pros="Popular and effective in trends.",
        cons="Late entries/exits and whipsaws when range-bound.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Visible Average Price",
        category="Trend Strength",
        description="Price level with highest traded volume in viewport (visible VWAP).",
        use="Identify local value/support/resistance.",
        pros="Intuitive anchor for current context.",
        cons="Depends on chart window selection.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Average True Range (ATR)",
        category="Volatility & Channels",
        description="Average of true ranges to quantify volatility.",
        use="Position sizing and stop placement.",
        pros="Universal volatility measure.",
        cons="Not directional.",
        rating=5.0,
    ),
    IndicatorDefinition(
        name="Bollinger Bands",
        category="Volatility & Channels",
        description="Bands at ± standard deviations around a moving average.",
        use="Volatility squeezes, mean reversion, and breakout cues.",
        pros="Versatile for both trend and mean reversion.",
        cons="Bands can stay wide during trends causing false reversions.",
        rating=4.5,
    ),
    IndicatorDefinition(
        name="Keltner Channels",
        category="Volatility & Channels",
        description="EMA-based channel offset by ATR.",
        use="Complement Bollinger for squeeze detection.",
        pros="Less sensitive to outliers.",
        cons="Requires tuning to instrument.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Donchian Channels",
        category="Volatility & Channels",
        description="Highest high/lowest low over lookback.",
        use="Breakout systems like Turtle Trading.",
        pros="Simple and rules-based.",
        cons="Subject to whipsaws and false breakouts.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Moving Average Envelope",
        category="Volatility & Channels",
        description="Fixed percentage bands around a moving average.",
        use="Mean reversion or overbought/oversold detection.",
        pros="Simple to interpret.",
        cons="Fixed width fails to adapt to volatility changes.",
        rating=2.5,
    ),
    IndicatorDefinition(
        name="Historical Volatility",
        category="Volatility & Channels",
        description="Statistical variance of price over a lookback.",
        use="Option pricing, risk analysis.",
        pros="Objective statistical measure.",
        cons="Backward-looking only.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Mass Index",
        category="Volatility & Channels",
        description="Range expansion indicator aimed at spotting reversals.",
        use="Signal triggers when threshold reached and then drops.",
        pros="Views reversals differently than standard oscillators.",
        cons="Niche and lagging.",
        rating=2.5,
    ),
    IndicatorDefinition(
        name="Choppiness Index",
        category="Volatility & Channels",
        description="Measures whether market is trending or choppy.",
        use="Avoid deploying trend strategies in choppy environments.",
        pros="Improves strategy selection.",
        cons="Subjective threshold settings.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Average Day Range (ADR)",
        category="Volatility & Channels",
        description="Average daily high-low range.",
        use="Set intraday targets and stops.",
        pros="Practical for day traders.",
        cons="Market regime shifts impact reliability.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Gaps",
        category="Volatility & Channels",
        description="Price gaps between sessions.",
        use="Gap-fill or continuation strategies.",
        pros="Clear actionable events.",
        cons="Behavior varies by market/time.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Pivot Points",
        category="Price Structure",
        description="Standard or high-low derived daily support/resistance levels.",
        use="Intraday trading levels widely watched.",
        pros="Common reference for traders.",
        cons="Can fail during strong trends.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Auto Fibonacci Retracement",
        category="Price Structure",
        description="Automatically drawn fib retracement levels between swings.",
        use="Project potential support/resistance.",
        pros="Common target levels.",
        cons="Depends heavily on swing selection.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Auto Fibonacci Extension",
        category="Price Structure",
        description="Automatic projection of fib extension targets.",
        use="Set upside/downside targets beyond swing.",
        pros="Widely referenced by traders.",
        cons="Conflicting levels if anchors differ.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Auto Pitchfork / Auto Trendlines",
        category="Price Structure",
        description="Automated drawing of Andrews' Pitchfork or key trendlines.",
        use="Channel price action and spot mean reversion levels.",
        pros="Saves manual chart work.",
        cons="Automatic anchoring can be wrong; requires validation.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Zig Zag",
        category="Price Structure",
        description="Filters minor moves to show major swings.",
        use="Identify structure, derive fibs/pivots.",
        pros="Declutters chart swings.",
        cons="Repainting nature, retrospective.",
        rating=3.5,
    ),
    IndicatorDefinition(
        name="Fractals",
        category="Price Structure",
        description="Local swing highs/lows marking pivots.",
        use="Support/resistance identification and stops.",
        pros="Easy to observe on charts.",
        cons="Repaint until candle closes.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Price Oscillator / Price Targets",
        category="Price Structure",
        description="Measures difference between two price averages to derive targets.",
        use="Generate divergence signals or objective targets.",
        pros="Flexible for custom strategies.",
        cons="Reliability varies by method.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Correlation Coefficient",
        category="Statistical Tools",
        description="Statistical correlation between two time-series.",
        use="Pairs trading and diversification checks.",
        pros="Objective dependency measurement.",
        cons="Correlation changes over time.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Rank Correlation Index (RCI)",
        category="Statistical Tools",
        description="Ranking-based momentum/correlation metric across windows.",
        use="Momentum timing using rank statistics.",
        pros="Robust to outliers.",
        cons="Niche and less intuitive.",
        rating=2.5,
    ),
    IndicatorDefinition(
        name="Seasonality",
        category="Cycles & Other",
        description="Historical patterns by time of year or day.",
        use="Overlay seasonal bias on trade ideas.",
        pros="Adds probabilistic edge when valid.",
        cons="Subject to regime changes and sample bias.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Moon Phases",
        category="Cycles & Other",
        description="Esoteric cycle indicator referencing lunar phases.",
        use="Occasionally combined with seasonality for niche systems.",
        pros="Niche edges according to some traders.",
        cons="No consistent statistical edge for most markets.",
        rating=1.5,
    ),
    IndicatorDefinition(
        name="Klinger Oscillator",
        category="Specialized",
        description="Volume flow indicator comparing long and short EMAs.",
        use="Confirm money flow and detect divergences.",
        pros="Combines momentum with volume.",
        cons="Complex interpretation.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Elder Force Index",
        category="Specialized",
        description="Price change multiplied by volume to show force.",
        use="Confirm move strength and pullbacks.",
        pros="Straightforward calculation.",
        cons="Noisy on small timeframes.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Balance of Power (BOP)",
        category="Specialized",
        description="Measures buying vs selling pressure within each bar.",
        use="Confirm trend direction or turning points.",
        pros="Sensitive to intrabar dynamics.",
        cons="Often needs smoothing.",
        rating=2.5,
    ),
    IndicatorDefinition(
        name="Ease of Movement (EOM)",
        category="Specialized",
        description="Relates price change to volume to gauge effort.",
        use="Identify moves accomplished with little resistance.",
        pros="Unique perspective on move quality.",
        cons="Niche indicator, less tested.",
        rating=2.5,
    ),
    IndicatorDefinition(
        name="Open Interest",
        category="Derivatives Metrics",
        description="Number of outstanding derivative contracts.",
        use="Confirm futures/options trends via participation.",
        pros="Essential for derivatives traders.",
        cons="Needs option chain context for interpretation.",
        rating=4.0,
    ),
    IndicatorDefinition(
        name="Rob Booker Indicators",
        category="Proprietary",
        description="Suite of author-specific tools like Knoxville Divergence or Ghost Pivots.",
        use="Follow the designer's intraday pivot rules.",
        pros="Can work within intended environment.",
        cons="Proprietary and may not generalize; requires backtests.",
        rating=3.0,
    ),
    IndicatorDefinition(
        name="Technical Ratings",
        category="Composite Scores",
        description="Platform-generated buy/hold/sell consensus.",
        use="Quick screening of assets.",
        pros="Saves time aggregating signals.",
        cons="Black-box and platforms often disagree.",
        rating=3.0,
    ),
]

INDICATOR_LOOKUP: Dict[str, IndicatorDefinition] = {
    indicator.name.lower(): indicator for indicator in INDICATORS
}


def get_indicator(name: str) -> Optional[IndicatorDefinition]:
    """Return indicator definition by case-insensitive name."""
    return INDICATOR_LOOKUP.get(name.lower())


def indicators_by_category(category: str) -> List[IndicatorDefinition]:
    """List indicators belonging to a category (case-insensitive)."""
    target = category.lower()
    return [indicator for indicator in INDICATORS if indicator.category.lower() == target]


def top_indicators(min_rating: float = 4.0) -> List[IndicatorDefinition]:
    """Return indicators with rating >= min_rating sorted by rating descending."""
    filtered = [indicator for indicator in INDICATORS if indicator.rating >= min_rating]
    return sorted(filtered, key=lambda item: item.rating, reverse=True)


def search_indicators(keyword: str) -> List[IndicatorDefinition]:
    """
    Simple keyword search across name, description, and use fields.
    """
    key = keyword.lower()
    matches: List[IndicatorDefinition] = []
    for indicator in INDICATORS:
        haystack = " ".join([indicator.name, indicator.description, indicator.use]).lower()
        if key in haystack:
            matches.append(indicator)
    return matches


__all__ = [
    "IndicatorDefinition",
    "INDICATORS",
    "INDICATOR_LOOKUP",
    "get_indicator",
    "indicators_by_category",
    "top_indicators",
    "search_indicators",
]
