"""
Linear regression channel Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class LinearRegressionChannel:
    """Placeholder implementation for the Linear regression channel indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Linear regression channel value once implemented."""
        raise NotImplementedError("Implement the Linear regression channel calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Linear regression channel values once implemented."""
        raise NotImplementedError("Implement the rolling Linear regression channel calculation.")
