"""
Mc Ginley Dynamic Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class McGinleyDynamic:
    """Placeholder implementation for the Mc Ginley Dynamic indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Mc Ginley Dynamic value once implemented."""
        raise NotImplementedError("Implement the Mc Ginley Dynamic calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Mc Ginley Dynamic values once implemented."""
        raise NotImplementedError("Implement the rolling Mc Ginley Dynamic calculation.")
