"""
Moon phases Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class MoonPhases:
    """Placeholder implementation for the Moon phases indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Moon phases value once implemented."""
        raise NotImplementedError("Implement the Moon phases calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Moon phases values once implemented."""
        raise NotImplementedError("Implement the rolling Moon phases calculation.")
