"""
Moving average simple Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class MovingAverageSimple:
    """Placeholder implementation for the Moving average simple indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Moving average simple value once implemented."""
        raise NotImplementedError("Implement the Moving average simple calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Moving average simple values once implemented."""
        raise NotImplementedError("Implement the rolling Moving average simple calculation.")
