"""
Moving average exponential Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class MovingAverageExponential:
    """Placeholder implementation for the Moving average exponential indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Moving average exponential value once implemented."""
        raise NotImplementedError("Implement the Moving average exponential calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Moving average exponential values once implemented."""
        raise NotImplementedError("Implement the rolling Moving average exponential calculation.")
