"""
Moving average convergence divergence Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class MovingAverageConvergenceDivergence:
    """Placeholder implementation for the Moving average convergence divergence indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Moving average convergence divergence value once implemented."""
        raise NotImplementedError("Implement the Moving average convergence divergence calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Moving average convergence divergence values once implemented."""
        raise NotImplementedError("Implement the rolling Moving average convergence divergence calculation.")
