"""
Moving average weighted Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class MovingAverageWeighted:
    """Placeholder implementation for the Moving average weighted indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Moving average weighted value once implemented."""
        raise NotImplementedError("Implement the Moving average weighted calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Moving average weighted values once implemented."""
        raise NotImplementedError("Implement the rolling Moving average weighted calculation.")
