"""
Net volume Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class NetVolume:
    """Placeholder implementation for the Net volume indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Net volume value once implemented."""
        raise NotImplementedError("Implement the Net volume calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Net volume values once implemented."""
        raise NotImplementedError("Implement the rolling Net volume calculation.")
