"""
On balance volume Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class OnBalanceVolume:
    """Placeholder implementation for the On balance volume indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single On balance volume value once implemented."""
        raise NotImplementedError("Implement the On balance volume calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling On balance volume values once implemented."""
        raise NotImplementedError("Implement the rolling On balance volume calculation.")
