"""
Pivot points high low Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class PivotPointsHighLow:
    """Placeholder implementation for the Pivot points high low indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Pivot points high low value once implemented."""
        raise NotImplementedError("Implement the Pivot points high low calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Pivot points high low values once implemented."""
        raise NotImplementedError("Implement the rolling Pivot points high low calculation.")
