"""
Rank correlation index Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class RankCorrelationIndex:
    """Placeholder implementation for the Rank correlation index indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Rank correlation index value once implemented."""
        raise NotImplementedError("Implement the Rank correlation index calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Rank correlation index values once implemented."""
        raise NotImplementedError("Implement the rolling Rank correlation index calculation.")
