"""
Relative strength Index Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class RelativeStrengthIndex:
    """Placeholder implementation for the Relative strength Index indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Relative strength Index value once implemented."""
        raise NotImplementedError("Implement the Relative strength Index calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Relative strength Index values once implemented."""
        raise NotImplementedError("Implement the rolling Relative strength Index calculation.")
