"""
Seasonality Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class Seasonality:
    """Placeholder implementation for the Seasonality indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Seasonality value once implemented."""
        raise NotImplementedError("Implement the Seasonality calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Seasonality values once implemented."""
        raise NotImplementedError("Implement the rolling Seasonality calculation.")
