"""
SMI Ergodic indicator Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class SmiErgodicIndicator:
    """Placeholder implementation for the SMI Ergodic indicator indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single SMI Ergodic indicator value once implemented."""
        raise NotImplementedError("Implement the SMI Ergodic indicator calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling SMI Ergodic indicator values once implemented."""
        raise NotImplementedError("Implement the rolling SMI Ergodic indicator calculation.")
