"""
SMI Ergodic oscillator Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class SmiErgodicOscillator:
    """Placeholder implementation for the SMI Ergodic oscillator indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single SMI Ergodic oscillator value once implemented."""
        raise NotImplementedError("Implement the SMI Ergodic oscillator calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling SMI Ergodic oscillator values once implemented."""
        raise NotImplementedError("Implement the rolling SMI Ergodic oscillator calculation.")
