"""
Smoothed moving average Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class SmoothedMovingAverage:
    """Placeholder implementation for the Smoothed moving average indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Smoothed moving average value once implemented."""
        raise NotImplementedError("Implement the Smoothed moving average calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Smoothed moving average values once implemented."""
        raise NotImplementedError("Implement the rolling Smoothed moving average calculation.")
