"""
Time weighted average price Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class TimeWeightedAveragePrice:
    """Placeholder implementation for the Time weighted average price indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Time weighted average price value once implemented."""
        raise NotImplementedError("Implement the Time weighted average price calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Time weighted average price values once implemented."""
        raise NotImplementedError("Implement the rolling Time weighted average price calculation.")
