"""
Trading sessions Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class TradingSessions:
    """Placeholder implementation for the Trading sessions indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Trading sessions value once implemented."""
        raise NotImplementedError("Implement the Trading sessions calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Trading sessions values once implemented."""
        raise NotImplementedError("Implement the rolling Trading sessions calculation.")
