"""
Up / Down Volume Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class UpDownVolume:
    """Placeholder implementation for the Up / Down Volume indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Up / Down Volume value once implemented."""
        raise NotImplementedError("Implement the Up / Down Volume calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Up / Down Volume values once implemented."""
        raise NotImplementedError("Implement the rolling Up / Down Volume calculation.")
