"""
Visible average price Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class VisibleAveragePrice:
    """Placeholder implementation for the Visible average price indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Visible average price value once implemented."""
        raise NotImplementedError("Implement the Visible average price calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Visible average price values once implemented."""
        raise NotImplementedError("Implement the rolling Visible average price calculation.")
