"""
Volume delta Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class VolumeDelta:
    """Placeholder implementation for the Volume delta indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Volume delta value once implemented."""
        raise NotImplementedError("Implement the Volume delta calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Volume delta values once implemented."""
        raise NotImplementedError("Implement the rolling Volume delta calculation.")
