"""
Volume weighted average price Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class VolumeWeightedAveragePrice:
    """Placeholder implementation for the Volume weighted average price indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Volume weighted average price value once implemented."""
        raise NotImplementedError("Implement the Volume weighted average price calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Volume weighted average price values once implemented."""
        raise NotImplementedError("Implement the rolling Volume weighted average price calculation.")
