"""
Vortex indicator Indicator Placeholder

This module was auto-generated by `generate_indicator_stubs.py`. Replace the
placeholder methods with the real calculation logic and tests.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Sequence


@dataclass
class VortexIndicator:
    """Placeholder implementation for the Vortex indicator indicator."""

    lookback: int = 14

    def calculate(self, series: Sequence[float]) -> Optional[float]:
        """Return a single Vortex indicator value once implemented."""
        raise NotImplementedError("Implement the Vortex indicator calculation.")

    def calculate_series(self, series: Sequence[float]) -> List[Optional[float]]:
        """Return rolling Vortex indicator values once implemented."""
        raise NotImplementedError("Implement the rolling Vortex indicator calculation.")
